version: '3.1'
services:
  db:
    image: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=admin
    ports:
      - "3307:3306"
    volumes:
      - './volumes:/var/lib/mysql'